version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - fullstack

  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: sandbox
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    networks:
      - fullstack
  app:
    depends_on:
      - postgres
      - redis
    build: .
    ports:
    - "8081:8081"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge

